### ISSUE TITLE
Migrate website tutorials

### ISSUE THREAD

**Issue by hyoo** [PATRIC3/p3_docs#1]
Genomics
- [x] Genome Assembly (updated)
- [x] Genome Annotation (updated)
- [x] Private Genome (updated)
- [x] BLAST Service (updated)
- [x] Similar Genome Finder (updated)
- [x] Variation Analysis Service (updated)
- [x] Phylogenetic Tree Building (updated)

Transcriptomics
- [x] Expression Import (updated)
- [x] RNA-Seq Data Submission (updated)
- [x] Transcriptomics Page (updated)

Protein Tools
- [x] Protein Family Sorter (updated)
- [x] Proteome Comparison (updated)
- [x] Excel formatting for Proteome Comparison

Metabolomics
- [x] Comparing Pathways (updated)

Others
- [x] Genome Groups (updated)
- [x] Antimicrobial Resistance (updated)

**Comment by dawenx** [comment]
harry, how to add "check" to above check box? also, "expression import" is under "Transcriptomics" in above list, but it's under "Genomics" in the docs tree.

**Comment by hyoo** [comment]
@dawenx i fixed the category of expression import. https://github.com/PATRIC3/p3_docs/commit/a3743ba64afb6f990be92a82515e5491ba9c19bd

**Comment by hyoo** [comment]
all done!
